apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-task-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-task
  template:
    metadata:
      labels:
        app: brain-task
    spec:
      containers:
      - name: brain-task
        image: 213375652280.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app:latest
        ports:
        - containerPort: 80
