apiVersion: v1
kind: Service
metadata:
  name: brain-task-service
spec:
  type: LoadBalancer
  selector:
    app: brain-task
  ports:
  - port: 3000       # External / Host port
    targetPort: 80   # Container port
